const std = @import("std");

var STDX_MOD: ?*std.Build.Module = null;
var STDX_TEST_STEP: *std.Build.Step = undefined;
var ECS_MOD: ?*std.Build.Module = null;
var PROTOCOL_MOD: ?*std.Build.Module = null;
var PROTOCOL_TEST_STEP: *std.Build.Step = undefined;
var DB_MOD: ?*std.Build.Module = null;
var DB_TEST_STEP: *std.Build.Step = undefined;
var DOMAIN_MOD: ?*std.Build.Module = null;
var DOMAIN_TEST_STEP: *std.Build.Step = undefined;
var SERVER_MOD: ?*std.Build.Module = null;
var SERVER_TEST_STEP: *std.Build.Step = undefined;
var WORLD_MOD: ?*std.Build.Module = null;
var WORLD_TEST_STEP: *std.Build.Step = undefined;
var OPTIONS: ?*std.Build.Step.Options = null;

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    addOptions(b);
    try addStdx(b, target, optimize);
    try addEcs(b, target, optimize);
    try addDomain(b, target, optimize);
    try addProtocol(b, target, optimize);
    try addDb(b, target, optimize);
    try addWorld(b, target, optimize);
    try addServer(b, target, optimize);

    const all_test = b.step("all-test", "Run all module tests");
    all_test.dependOn(STDX_TEST_STEP);
    all_test.dependOn(DOMAIN_TEST_STEP);
    all_test.dependOn(PROTOCOL_TEST_STEP);
    all_test.dependOn(DB_TEST_STEP);
    all_test.dependOn(WORLD_TEST_STEP);
    all_test.dependOn(SERVER_TEST_STEP);
}

/// Declares shared build options once and exposes them to every module via
/// `build_config`. Any module needing a build option should use this global
/// set rather than defining its own.
fn addOptions(b: *std.Build) void {
    const enable_verbose_packet_log = b.option(bool, "enable-verbose-packet-log", "Will display all packets and their byte representation, useful for debugging protocol correctness") orelse false;

    const options = b.addOptions();
    options.addOption(bool, "enable-verbose-packet-log", enable_verbose_packet_log);
    OPTIONS = options;
}

fn addEcs(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !void {
    ECS_MOD = b.dependency("entt", .{
        .target = target,
        .optimize = optimize,
    }).module("zig-ecs");
}

fn addDomain(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !void {
    const game_data_mod = try generateGameDataModule(b);
    const stdx_mod = STDX_MOD orelse return error.MissingModule;

    const mod = b.createModule(.{
        .root_source_file = b.path("src/domain/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "game_data", .module = game_data_mod },
            .{ .name = "stdx", .module = stdx_mod },
        },
    });
    DOMAIN_MOD = mod;

    const tst = b.addTest(.{ .root_module = mod });
    const run = b.addRunArtifact(tst);
    if (b.args) |args| {
        run.addArgs(args);
    }
    DOMAIN_TEST_STEP = b.step("domain-test", "Run domain tests");
    DOMAIN_TEST_STEP.dependOn(&run.step);
}

const GameDataColumn = struct {
    name: []const u8,
    kind: GameDataKind,
};

const GameDataKind = enum {
    boolean,
    integer,
    float,
    string,

    fn zigType(self: GameDataKind) []const u8 {
        return switch (self) {
            .boolean => "bool",
            .integer => "i64",
            .float => "f64",
            .string => "[]const u8",
        };
    }
};

/// Scans `src/game_data/*.json` at configure time and emits a generated
/// `game_data` module. Each `foo.json` (a JSON array of homogeneous objects)
/// becomes a generated `foo.zig` exposing `Row` (the inferred element struct)
/// and `rows: []const Row`, re-exported as `game_data.foo`. `build()` re-runs
/// on every `zig build`, so edits to the JSON files are picked up automatically.
fn generateGameDataModule(b: *std.Build) !*std.Build.Module {
    const io = b.graph.io;
    const gpa = b.allocator;

    var data_dir = try b.build_root.handle.openDir(io, "src/game_data", .{ .iterate = true });
    defer data_dir.close(io);

    var stems: std.ArrayList([]const u8) = .empty;
    var it = data_dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".json")) continue;
        const stem = entry.name[0 .. entry.name.len - ".json".len];
        try stems.append(gpa, try gpa.dupe(u8, stem));
    }

    std.mem.sort([]const u8, stems.items, {}, struct {
        fn lessThan(_: void, a: []const u8, c: []const u8) bool {
            return std.mem.lessThan(u8, a, c);
        }
    }.lessThan);

    const wf = b.addWriteFiles();

    var root_src: std.ArrayList(u8) = .empty;
    try root_src.appendSlice(gpa, "// GENERATED by build.zig from src/game_data/*.json - DO NOT EDIT.\n");

    for (stems.items) |stem| {
        const json_bytes = try data_dir.readFileAlloc(io, b.fmt("{s}.json", .{stem}), gpa, .limited(1 << 22));
        const file_src = try generateGameDataFile(b, json_bytes);
        _ = wf.add(b.fmt("{s}.zig", .{stem}), file_src);
        try root_src.appendSlice(gpa, b.fmt("pub const {s} = @import(\"{s}.zig\");\n", .{ stem, stem }));
    }

    const root = wf.add("game_data.zig", root_src.items);
    return b.createModule(.{ .root_source_file = root });
}

fn generateGameDataFile(b: *std.Build, json_bytes: []const u8) ![]const u8 {
    const gpa = b.allocator;

    const parsed = try std.json.parseFromSlice(std.json.Value, gpa, json_bytes, .{});
    defer parsed.deinit();

    if (parsed.value != .array) return error.ExpectedJsonArray;
    const elems = parsed.value.array.items;

    var columns: std.ArrayList(GameDataColumn) = .empty;
    if (elems.len > 0) {
        if (elems[0] != .object) return error.ExpectedJsonObject;
        for (elems[0].object.keys()) |key| {
            try columns.append(gpa, .{ .name = key, .kind = .integer });
        }
        for (columns.items) |*col| {
            var kind: ?GameDataKind = null;
            for (elems) |elem| {
                if (elem != .object) return error.ExpectedJsonObject;
                if (elem.object.get(col.name)) |v| kind = mergeKind(kind, v);
            }
            col.kind = kind orelse .string;
        }
    }

    var src: std.ArrayList(u8) = .empty;
    try src.appendSlice(gpa, "// GENERATED from a src/game_data/*.json file by build.zig - DO NOT EDIT.\n");
    try src.appendSlice(gpa, "pub const Row = struct {\n");
    for (columns.items) |col| {
        try src.appendSlice(gpa, b.fmt("    @\"{s}\": {s},\n", .{ col.name, col.kind.zigType() }));
    }
    try src.appendSlice(gpa, "};\n\npub const rows: []const Row = &.{\n");
    for (elems) |elem| {
        try src.appendSlice(gpa, "    .{ ");
        for (columns.items) |col| {
            try src.appendSlice(gpa, b.fmt(".@\"{s}\" = ", .{col.name}));
            try appendGameDataValue(b, &src, col.kind, elem.object.get(col.name));
            try src.appendSlice(gpa, ", ");
        }
        try src.appendSlice(gpa, "},\n");
    }
    try src.appendSlice(gpa, "};\n");
    return src.items;
}

fn mergeKind(cur: ?GameDataKind, v: std.json.Value) ?GameDataKind {
    const k: GameDataKind = switch (v) {
        .bool => .boolean,
        .integer => .integer,
        .float, .number_string => .float,
        .string => .string,
        else => return cur,
    };
    const c = cur orelse return k;
    if (c == k) return k;
    if ((c == .integer and k == .float) or (c == .float and k == .integer)) return .float;
    return .string;
}

fn appendGameDataValue(b: *std.Build, src: *std.ArrayList(u8), kind: GameDataKind, v_opt: ?std.json.Value) !void {
    const gpa = b.allocator;
    const v = v_opt orelse {
        try src.appendSlice(gpa, switch (kind) {
            .boolean => "false",
            .integer, .float => "0",
            .string => "\"\"",
        });
        return;
    };
    switch (kind) {
        .boolean => try src.appendSlice(gpa, if (v == .bool and v.bool) "true" else "false"),
        .integer => try src.appendSlice(gpa, b.fmt("{d}", .{if (v == .integer) v.integer else 0})),
        .float => switch (v) {
            .float => |f| try src.appendSlice(gpa, b.fmt("{d}", .{f})),
            .integer => |i| try src.appendSlice(gpa, b.fmt("{d}", .{i})),
            .number_string => |s| try src.appendSlice(gpa, s),
            else => try src.appendSlice(gpa, "0"),
        },
        .string => {
            try src.appendSlice(gpa, "\"");
            try appendGameDataEscaped(b, src, if (v == .string) v.string else "");
            try src.appendSlice(gpa, "\"");
        },
    }
}

fn appendGameDataEscaped(b: *std.Build, src: *std.ArrayList(u8), s: []const u8) !void {
    const gpa = b.allocator;
    for (s) |ch| {
        switch (ch) {
            '\\' => try src.appendSlice(gpa, "\\\\"),
            '"' => try src.appendSlice(gpa, "\\\""),
            '\n' => try src.appendSlice(gpa, "\\n"),
            '\t' => try src.appendSlice(gpa, "\\t"),
            '\r' => try src.appendSlice(gpa, "\\r"),
            else => try src.append(gpa, ch),
        }
    }
}

fn addDb(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !void {
    const pg_mod = b.dependency("pg", .{ .target = target, .optimize = optimize }).module("pg");
    const domain_mod = DOMAIN_MOD orelse return error.MissingModule;

    const mod = b.createModule(.{
        .root_source_file = b.path("src/db/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "pg", .module = pg_mod },
            .{ .name = "domain", .module = domain_mod },
        },
    });
    DB_MOD = mod;

    const tst = b.addTest(.{ .root_module = mod });
    const run = b.addRunArtifact(tst);
    if (b.args) |args| {
        run.addArgs(args);
    }
    DB_TEST_STEP = b.step("db-test", "Run db tests");
    DB_TEST_STEP.dependOn(&run.step);
}

fn addWorld(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !void {
    const stdx_mod = STDX_MOD orelse return error.MissingModule;
    const ecs_mod = ECS_MOD orelse return error.MissingModule;
    const domain_mod = DOMAIN_MOD orelse return error.MissingModule;
    const protocol_mod = PROTOCOL_MOD orelse return error.MissingModule;
    const options = OPTIONS orelse return error.MissingModule;

    const mod = b.createModule(.{
        .root_source_file = b.path("src/world/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "stdx", .module = stdx_mod },
            .{ .name = "ecs", .module = ecs_mod },
            .{ .name = "domain", .module = domain_mod },
            .{ .name = "protocol", .module = protocol_mod },
        },
    });
    mod.addOptions("build_config", options);
    WORLD_MOD = mod;
    const tst = b.addTest(.{
        .root_module = mod,
    });
    const run = b.addRunArtifact(tst);
    if (b.args) |args| {
        run.addArgs(args);
    }
    WORLD_TEST_STEP = b.step("world-test", "Run world tests");
    WORLD_TEST_STEP.dependOn(&run.step);
}

fn addStdx(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !void {
    const mod = b.createModule(.{
        .root_source_file = b.path("src/stdx/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    STDX_MOD = mod;
    const tst = b.addTest(.{
        .root_module = mod,
    });
    const run = b.addRunArtifact(tst);
    if (b.args) |args| {
        run.addArgs(args);
    }
    STDX_TEST_STEP = b.step("stdx-test", "Run stdx tests");
    STDX_TEST_STEP.dependOn(&run.step);
}

fn addProtocol(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !void {
    const domain_mod = DOMAIN_MOD orelse return error.MissingModule;
    const stdx_mod = STDX_MOD orelse return error.MissingModule;
    const options = OPTIONS orelse return error.MissingModule;
    const mod = b.createModule(.{
        .root_source_file = b.path("src/protocol/Protocol.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "domain", .module = domain_mod },
            .{ .name = "stdx", .module = stdx_mod },
        },
    });
    mod.addOptions("build_config", options);
    PROTOCOL_MOD = mod;
    const tst = b.addTest(.{
        .root_module = mod,
    });
    const run = b.addRunArtifact(tst);
    if (b.args) |args| {
        run.addArgs(args);
    }
    PROTOCOL_TEST_STEP = b.step("protocol-test", "Run protocol tests");
    PROTOCOL_TEST_STEP.dependOn(&run.step);
}

fn addServer(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !void {
    const stdx_mod = STDX_MOD orelse return error.MissingModule;
    const protocol_mod = PROTOCOL_MOD orelse return error.MissingModule;
    const db_mod = DB_MOD orelse return error.MissingModule;
    const domain_mod = DOMAIN_MOD orelse return error.MissingModule;
    const world_mod = WORLD_MOD orelse return error.MissingModule;
    const pg_mod = b.dependency("pg", .{ .target = target, .optimize = optimize }).module("pg");
    const options = OPTIONS orelse return error.MissingModule;

    const mod = b.createModule(.{
        .root_source_file = b.path("src/server/main.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "stdx", .module = stdx_mod },
            .{ .name = "protocol", .module = protocol_mod },
            .{ .name = "db", .module = db_mod },
            .{ .name = "domain", .module = domain_mod },
            .{ .name = "world", .module = world_mod },
            .{ .name = "pg", .module = pg_mod },
        },
    });
    mod.addOptions("build_config", options);

    SERVER_MOD = mod;
    const exe = b.addExecutable(.{
        .name = "arenacraft2",
        .root_module = mod,
    });
    const install = b.addInstallArtifact(exe, .{});
    b.getInstallStep().dependOn(&install.step); // plain `zig build`
    const build_step = b.step("server-build", "Build and install server");
    build_step.dependOn(&install.step);
    const run = b.addRunArtifact(exe);
    run.step.dependOn(&install.step);
    if (b.args) |args| {
        run.addArgs(args);
    }
    const run_step = b.step("server-run", "Run server");
    run_step.dependOn(&run.step);
    const tst = b.addTest(.{
        .root_module = mod,
    });
    const test_run = b.addRunArtifact(tst);
    if (b.args) |args| {
        test_run.addArgs(args);
    }
    SERVER_TEST_STEP = b.step("server-test", "Run server tests");
    SERVER_TEST_STEP.dependOn(&test_run.step);
}
