name: arenacraft_deps

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: arenacraft
      POSTGRES_PASSWORD: arenacraft
      POSTGRES_DB: arenacraft
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arenacraft -d arenacraft"]
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: flat
    ports:
      - "6664:8080"
    depends_on:
      - db

  app:
    image: ghcr.io/dawidcxx/arenacraft2:latest
    profiles:
      - full
    environment:
      DATABASE_URL: postgresql://arenacraft:arenacraft@db:5432/arenacraft
    ports:
      - "3724:3724"
      - "8085:8085"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
