-- Squashed schema snapshot taken from the running database (pg_dump --schema-only).
-- Do not edit retroactively; add new migrations for further schema changes.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE TABLE public.realms (
    id smallint NOT NULL,
    realmname character varying(32) NOT NULL
);

CREATE TABLE public.world_instances (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    map_id integer NOT NULL,
    name character varying(64) NOT NULL,
    kind character varying(16) NOT NULL,
    static boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT world_instances_kind_valid CHECK (kind IN ('static', 'arena', 'battleground', 'dungeon'))
);

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    username character varying(16) NOT NULL,
    email character varying(255),
    salt bytea NOT NULL,
    verifier bytea NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone,
    last_ip inet,
    CONSTRAINT accounts_salt_len CHECK ((octet_length(salt) = 32)),
    CONSTRAINT accounts_username_len CHECK (((char_length((username)::text) >= 2) AND (char_length((username)::text) <= 16))),
    CONSTRAINT accounts_username_uppercase CHECK (((username)::text = upper((username)::text))),
    CONSTRAINT accounts_verifier_len CHECK ((octet_length(verifier) = 32))
);

CREATE SEQUENCE public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.accounts_id_seq OWNED BY public.accounts.id;

ALTER TABLE public.accounts ALTER COLUMN id SET DEFAULT nextval('public.accounts_id_seq'::regclass);

CREATE TABLE public.characters (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    guid bigint NOT NULL,
    account_id bigint NOT NULL,
    realm_id smallint NOT NULL,
    current_instance_id uuid,
    name character varying(12) NOT NULL,
    race_id smallint NOT NULL,
    class_id smallint NOT NULL,
    gender smallint DEFAULT 0 NOT NULL,
    skin smallint DEFAULT 0 NOT NULL,
    face smallint DEFAULT 0 NOT NULL,
    hair_style smallint DEFAULT 0 NOT NULL,
    hair_color smallint DEFAULT 0 NOT NULL,
    facial_hair smallint DEFAULT 0 NOT NULL,
    outfit_id smallint DEFAULT 0 NOT NULL,
    level smallint DEFAULT 1 NOT NULL,
    position_x real DEFAULT 0 NOT NULL,
    position_y real DEFAULT 0 NOT NULL,
    position_z real DEFAULT 0 NOT NULL,
    orientation real DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT characters_appearance_ranges CHECK (((skin >= 0) AND (skin <= 255) AND (face >= 0) AND (face <= 255) AND (hair_style >= 0) AND (hair_style <= 255) AND (hair_color >= 0) AND (hair_color <= 255) AND (facial_hair >= 0) AND (facial_hair <= 255) AND (outfit_id >= 0) AND (outfit_id <= 255))),
    CONSTRAINT characters_gender_range CHECK (((gender >= 0) AND (gender <= 1))),
    CONSTRAINT characters_guid_range CHECK (((guid >= 1) AND (guid <= '4294967295'::bigint))),
    CONSTRAINT characters_level_range CHECK (((level >= 1) AND (level <= 80))),
    CONSTRAINT characters_name_format CHECK (((name)::text ~ '^[A-Z][a-z]{1,11}$'::text))
);

ALTER TABLE public.characters ALTER COLUMN guid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.characters_guid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.character_equipment (
    character_id uuid NOT NULL,
    slot smallint NOT NULL,
    item_entry integer NOT NULL,
    enchant_id integer DEFAULT 0 NOT NULL,
    CONSTRAINT character_equipment_enchant_nonneg CHECK ((enchant_id >= 0)),
    CONSTRAINT character_equipment_entry_positive CHECK ((item_entry > 0)),
    CONSTRAINT character_equipment_slot_range CHECK (((slot >= 0) AND (slot <= 18)))
);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.character_equipment
    ADD CONSTRAINT character_equipment_pkey PRIMARY KEY (character_id, slot);

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_realm_name_unique UNIQUE (realm_id, name);

ALTER TABLE ONLY public.realms
    ADD CONSTRAINT realms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.world_instances
    ADD CONSTRAINT world_instances_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX accounts_username_unique ON public.accounts USING btree (username);

CREATE INDEX character_equipment_character_idx ON public.character_equipment USING btree (character_id);

CREATE INDEX characters_account_realm_idx ON public.characters USING btree (account_id, realm_id);

CREATE UNIQUE INDEX characters_guid_unique ON public.characters USING btree (guid);

CREATE UNIQUE INDEX realms_realmname_key ON public.realms USING btree (realmname);

ALTER TABLE ONLY public.character_equipment
    ADD CONSTRAINT character_equipment_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.characters(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_current_instance_id_fkey FOREIGN KEY (current_instance_id) REFERENCES public.world_instances(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_realm_id_fkey FOREIGN KEY (realm_id) REFERENCES public.realms(id) ON DELETE CASCADE;

INSERT INTO public.realms (id, realmname) VALUES (1, 'ArenaCraft');

INSERT INTO public.world_instances (id, map_id, name, kind, static) VALUES
    ('902e5fd8-67da-4ed1-9803-ec6d8ccf8ff4', 0, 'Eastern Kingdoms', 'static', TRUE),
    ('5046cf90-e61b-4469-9acf-4c3b5600816b', 1, 'Kalimdor', 'static', TRUE),
    ('8c9dbf25-121a-4a3f-99d7-32f67cb24114', 530, 'Outland', 'static', TRUE),
    ('da6b4efb-f5ad-4a77-9a54-497c528c2a42', 609, 'Acherus', 'static', TRUE);
