CREATE TABLE world_instances (
  id UUID PRIMARY KEY,
  map_id INTEGER NOT NULL,
  name VARCHAR(64) NOT NULL,
  kind VARCHAR(16) NOT NULL,
  static BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT world_instances_kind_valid CHECK (kind IN ('static', 'arena', 'battleground', 'dungeon'))
);

INSERT INTO world_instances (id, map_id, name, kind, static) VALUES
  ('902e5fd8-67da-4ed1-9803-ec6d8ccf8ff4', 0, 'Eastern Kingdoms', 'static', TRUE),
  ('5046cf90-e61b-4469-9acf-4c3b5600816b', 1, 'Kalimdor', 'static', TRUE),
  ('8c9dbf25-121a-4a3f-99d7-32f67cb24114', 530, 'Outland', 'static', TRUE),
  ('da6b4efb-f5ad-4a77-9a54-497c528c2a42', 609, 'Acherus', 'static', TRUE);

CREATE TABLE characters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  guid BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

  account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  realm_id UUID NOT NULL REFERENCES realms(id) ON DELETE CASCADE,
  current_instance_id UUID NULL REFERENCES world_instances(id) ON DELETE SET NULL,

  name VARCHAR(12) NOT NULL,
  race_id SMALLINT NOT NULL,
  class_id SMALLINT NOT NULL,
  gender SMALLINT NOT NULL,

  skin SMALLINT NOT NULL,
  face SMALLINT NOT NULL,
  hair_style SMALLINT NOT NULL,
  hair_color SMALLINT NOT NULL,
  facial_hair SMALLINT NOT NULL,
  outfit_id SMALLINT NOT NULL,

  level SMALLINT NOT NULL DEFAULT 80,
  position_x REAL NOT NULL,
  position_y REAL NOT NULL,
  position_z REAL NOT NULL,
  orientation REAL NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT characters_guid_unique UNIQUE (guid),
  CONSTRAINT characters_guid_range CHECK (guid BETWEEN 1 AND 4294967295),
  CONSTRAINT characters_realm_name_unique UNIQUE (realm_id, name),
  CONSTRAINT characters_name_format CHECK (name ~ '^[A-Z][a-z]{1,11}$'),
  CONSTRAINT characters_gender_range CHECK (gender BETWEEN 0 AND 1),
  CONSTRAINT characters_appearance_ranges CHECK (
    skin BETWEEN 0 AND 255 AND
    face BETWEEN 0 AND 255 AND
    hair_style BETWEEN 0 AND 255 AND
    hair_color BETWEEN 0 AND 255 AND
    facial_hair BETWEEN 0 AND 255 AND
    outfit_id BETWEEN 0 AND 255
  ),
  CONSTRAINT characters_level_range CHECK (level BETWEEN 1 AND 80)
);

CREATE INDEX characters_account_realm_idx ON characters (account_id, realm_id);
