-- Convert accounts.id and realms.id from UUID to integer types to match the
-- Zig server (auth.zig / char.zig):
--   accounts.id         -> BIGINT
--   realms.id           -> SMALLINT
--   characters.account_id -> BIGINT
--   characters.realm_id   -> SMALLINT

DROP TABLE IF EXISTS character_equipment CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS world_instances CASCADE;
DROP TABLE IF EXISTS realms CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;

CREATE TABLE accounts (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(16) NOT NULL,
    email VARCHAR(255),
    salt BYTEA NOT NULL,
    verifier BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ,
    last_ip INET,
    CONSTRAINT accounts_username_uppercase CHECK (username::text = UPPER(username::text)),
    CONSTRAINT accounts_username_len CHECK (CHAR_LENGTH(username::text) >= 2 AND CHAR_LENGTH(username::text) <= 16),
    CONSTRAINT accounts_salt_len CHECK (OCTET_LENGTH(salt) = 32),
    CONSTRAINT accounts_verifier_len CHECK (OCTET_LENGTH(verifier) = 32)
);

CREATE UNIQUE INDEX accounts_username_unique ON accounts (username);

CREATE TABLE realms (
    id SMALLINT PRIMARY KEY,
    realmname VARCHAR(32) NOT NULL
);

CREATE UNIQUE INDEX realms_realmname_key ON realms (realmname);

INSERT INTO realms (id, realmname) VALUES (1, 'ArenaCraft');

CREATE TABLE world_instances (
    id UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    map_id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    kind VARCHAR(16) NOT NULL,
    static BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT world_instances_kind_valid CHECK (kind IN ('static', 'arena', 'battleground', 'dungeon'))
);

INSERT INTO world_instances (id, map_id, name, kind, static) VALUES
    ('902e5fd8-67da-4ed1-9803-ec6d8ccf8ff4', 0, 'Eastern Kingdoms', 'static', TRUE),
    ('5046cf90-e61b-4469-9acf-4c3b5600816b', 1, 'Kalimdor', 'static', TRUE),
    ('8c9dbf25-121a-4a3f-99d7-32f67cb24114', 530, 'Outland', 'static', TRUE),
    ('da6b4efb-f5ad-4a77-9a54-497c528c2a42', 609, 'Acherus', 'static', TRUE);

CREATE TABLE characters (
    id UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    guid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    realm_id SMALLINT NOT NULL REFERENCES realms(id) ON DELETE CASCADE,
    current_instance_id UUID REFERENCES world_instances(id) ON DELETE SET NULL,
    name VARCHAR(12) NOT NULL,
    race_id SMALLINT NOT NULL,
    class_id SMALLINT NOT NULL,
    gender SMALLINT NOT NULL DEFAULT 0,
    skin SMALLINT NOT NULL DEFAULT 0,
    face SMALLINT NOT NULL DEFAULT 0,
    hair_style SMALLINT NOT NULL DEFAULT 0,
    hair_color SMALLINT NOT NULL DEFAULT 0,
    facial_hair SMALLINT NOT NULL DEFAULT 0,
    outfit_id SMALLINT NOT NULL DEFAULT 0,
    level SMALLINT NOT NULL DEFAULT 1,
    position_x REAL NOT NULL DEFAULT 0,
    position_y REAL NOT NULL DEFAULT 0,
    position_z REAL NOT NULL DEFAULT 0,
    orientation REAL NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT characters_guid_range CHECK (guid >= 1 AND guid <= 4294967295),
    CONSTRAINT characters_name_format CHECK (name ~ '^[A-Z][a-z]{1,11}$'),
    CONSTRAINT characters_realm_name_unique UNIQUE (realm_id, name),
    CONSTRAINT characters_gender_range CHECK (gender >= 0 AND gender <= 1),
    CONSTRAINT characters_appearance_ranges CHECK (
        skin >= 0 AND skin <= 255 AND
        face >= 0 AND face <= 255 AND
        hair_style >= 0 AND hair_style <= 255 AND
        hair_color >= 0 AND hair_color <= 255 AND
        facial_hair >= 0 AND facial_hair <= 255 AND
        outfit_id >= 0 AND outfit_id <= 255),
    CONSTRAINT characters_level_range CHECK (level >= 1 AND level <= 80)
);

CREATE UNIQUE INDEX characters_guid_unique ON characters (guid);
CREATE INDEX characters_account_realm_idx ON characters (account_id, realm_id);

CREATE TABLE character_equipment (
    character_id UUID NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    slot SMALLINT NOT NULL,
    item_entry INTEGER NOT NULL,
    enchant_id INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT character_equipment_pkey PRIMARY KEY (character_id, slot),
    CONSTRAINT character_equipment_slot_range CHECK (slot >= 0 AND slot <= 18),
    CONSTRAINT character_equipment_entry_positive CHECK (item_entry > 0),
    CONSTRAINT character_equipment_enchant_nonneg CHECK (enchant_id >= 0)
);

CREATE INDEX character_equipment_character_idx ON character_equipment (character_id);
